custom_categories:
  - name: Signal
    children:
    - Signal
    - SignalProtocol
  - name: SignalProducer
    children:
    - SignalProducer
    - SignalProducerProtocol
  - name: Property
    children:
    - Property
    - MutableProperty
    - PropertyProtocol
    - MutablePropertyProtocol
  - name: Action
    children:
    - Action
  - name: Bindings
    children:
    - BindingTarget
    - BindingTargetProtocol
    - BindingSourceProtocol
  - name: Disposable
    children:
    - ActionDisposable    
    - CompositeDisposable    
    - SimpleDisposable
    - SerialDisposable
    - Disposable
  - name: Utilities
    children:
    - Atomic 
theme: fullwidth
hide_documentation_coverage: true
author: ReactiveCocoa
author_url: https://reactivecocoa.io/
github_url: https://github.com/ReactiveCocoa/ReactiveSwift/
dash_url: https://reactivecocoa.io/feeds/ReactiveSwift.xml
